version: '3'
services:
  gpt_academic_full_capability:
    image: "ghcr.io/binary-husky/gpt_academic_with_all_capacity:master"
    environment:
      API_KEY: 'sk-v4GyjBUplKxHqReW911540407626441bB916D2Ed85Fa3650'
      USE_PROXY: 'False'
      proxies: '{"http": "https://zmgpt.cc/v1", }'
      LLM_MODEL: 'gpt-3.5-turbo'
      AVAIL_LLM_MODELS: '["gpt-3.5-turbo", "gpt-4", "qianfan", "sparkv2", "spark", "chatglm"]'
      BAIDU_CLOUD_API_KEY: 'bTUtwEAveBrQipEowUvDwYWq'
      BAIDU_CLOUD_SECRET_KEY: 'jqXtLvXiVw6UNdjliATTS61rllG8Iuni'
      XFYUN_APPID: '53a8d816'
      XFYUN_API_SECRET: 'MjMxNDQ4NDE4MzM0OSNlNjQ2NTlhMTkx'
      XFYUN_API_KEY: '95ccdec285364869d17b33e75ee96447'
      ENABLE_AUDIO: 'False'
      API_URL_REDIRECT: '{"https://api.openai.com/v1/chat/completions": "https://zmgpt.cc/v1/chat/completions" }'
      DEFAULT_WORKER_NUM: '20'
      WEB_PORT: '12345'
      ADD_WAIFU: 'Ture'
      ALIYUN_APPKEY: 'RxPlZrM88DnAFkZK'
      THEME: 'Chuanhu-Small-and-Beautiful'
      ALIYUN_ACCESSKEY: 'LTAI5t6BrFUzxRXVGUWnekh1'
      ALIYUN_SECRET: 'eHmI20SVWIwQZxCiTD2bGQVspP9i68'
  
      # LOCAL_MODEL_DEVICE: 'cuda' # This line is a comment and should be adjusted or removed based on your needs.
